package edu.misc.EE;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;


public class Resistor {
	private static Log log = LogFactory.getLog(Resistor.class);
	
	public static void main(String[] args) {
		System.err.println("");
		System.err.println("Exercise 1-1...");
		System.err.println("Exercise 1-2");
		System.err.println("3/5 = " + (3D/5D));
		System.err.println("parallel(parallel(1D,1D)+1D, 1D) = " + (parallel(parallel(1D,1D)+1D, 1D)));
		System.err.println("5/3 = " + (5D/3D));
		System.err.println("(parallel(parallel(1D + 1D), 1D) + 1D) = " + (parallel(parallel(1D + 1D), 1D) + 1D));
		System.err.println("");
		System.err.println("Exercise 1-3");
		System.err.println("100 + (25||50)= Rtotal = " + (parallel(25D,50D) + 100D));
		System.err.println("Vr100 = 6V divided on 100 = " + (100*6/(parallel(25D,50D) + 100D)));
		System.err.println("Vr(25||50) = 6V divided on parallel(25D,50D) = " + (parallel(25D,50D)*6/(parallel(25D,50D) + 100D)));
		System.err.println("Isource = I in 100R = V/R = " + (100*6/(parallel(25D,50D) + 100D))/100D);
		System.err.println("Power generated by source = V^2/Rtotal = " + Math.pow(6, 2)/((parallel(25D,50D) + 100D)));
		System.err.println("Power dissipated in 100R = V^2/R = " + (Math.pow(100*6/(parallel(25D,50D) + 100D), 2))/100D);
		System.err.println("I on 25D of parallel(25D,50D) = V/R = " + ((parallel(25D,50D)*6/(parallel(25D,50D) + 100D))/25D));
		System.err.println("Power dissipated in 25D of parallel(25D,50D) = V^2/R = " + (Math.pow(parallel(25D,50D)*6/(parallel(25D,50D) + 100D), 2))/25D);
		System.err.println("I on 50D of parallel(25D,50D) = V/R = " + ((parallel(25D,50D)*6/(parallel(25D,50D) + 100D))/50D));
		System.err.println("Power dissipated in 50D of parallel(25D,50D) = V^2/R = " + (Math.pow(parallel(25D,50D)*6/(parallel(25D,50D) + 100D), 2))/50D);
		System.err.println("");
		System.err.println("problem 1-1...");
		System.err.println("problem 1-2");
		Double R = 1D;
		Double Rfinal = R;
		for (int i = 0; i < 100; i++) {
			Rfinal = parallel(R, Rfinal + R);
		}
		System.err.println("parallel(Rfinal + R, R) loop 100 times = " + Rfinal + " x R ");
		
		Rfinal = R;
		for (int i = 0; i < 100; i++) {
			Rfinal = parallel(3*R/2, Rfinal + 2*R);
		}
		System.err.println("parallel(3*R/2, Rfinal + 2*R) loop 100 times = " + Rfinal + " x R ");
		
		Rfinal = parallel(parallel(R, R)+R, 3*R/2);
		System.err.println("parallel(parallel(R, R)+R, 3*R/2) = " + Rfinal + " x R ");
		System.err.println("problem 1-3...");
		Double R1 = 100D;
		Double R2 = 25D;
		Double R3 = 50D;
		Double Vs = 6D;
		System.err.println("R1 + (R2||R3)= Rtotal = " + (parallel(R2,R3) + R1));
		System.err.println("Vr1 = R1*Vs/Rtotal = " + (R1*Vs/(parallel(R2,R3) + R1)));
		System.err.println("-Vr3 = Vr1 - Vs = " + (6-(R1*Vs/(parallel(R2,R3) + R1))));
		System.err.println("I3 = -Vr3/R3 = " + (-(Vs-(R1*Vs/(parallel(R2,R3) + R1)))/R3));
		System.err.println("I3 formula = (-(Vs-(R1*Vs/(parallel(R2,R3) + R1)))/R3) = " + (-(Vs-(R1*Vs/(parallel(R2,R3) + R1)))/R3));
		System.err.println("I3 formula = (-(Vs-(R1*Vs/((R2*R3/(R3+R2)) + R1)))/R3) = " + (-(Vs-(R1*Vs/((R2*R3/(R3+R2)) + R1)))/R3));
		
	}
	
	public static double parallel(Double... x) {
		Double sum = 0D;
		for (Double resistor : x) {
			sum += 1D/resistor;
		}
		return 1/sum;
	}
}
